apiVersion: v1
kind: ConfigMap
metadata:
    name: cloudflared-config
    namespace: cloudflared
data:
    config.yaml: ENC[AES256_GCM,data:3RopsaV88JYmBaJ8aJZq6nqmbr0otwpBfcHWYGar8sWHe8O9cDTC4ltxfB5xZzWdU8Pp6jC2DNd6tVIfNDnrSU0IRsg55fFUIalED/NNrF4axuuLKb6ruvPCpvjy9MUpZ0pEoHxUGJYNjtJPRmwMarCnSIOF7T3dyGUM17L8MVRbdxR5hUTA9CFVD0oAemhZCWPJn/cZ5QswexO9vkMuIakBl0YJ2y+ttWBYhaQ82oIgUfh8BJT0FOFUKWCbc3VUpTHtLnFwtMs53FXaexbVQ8WZQ9Qyv06jNVyteCc/w3xicTNZVh1SkVBIySJlDCwhir1d5Gu5SgabZ9dV2C9fPGHtBYlkjsX+dBdCw+DyUGIidXLjIgTUfdyX+bj8BgbKJZAE/R1ECYJBXUjBUmBIRiaqIumSTtoGtFEHbmEJduQgqCioMSZj8pxv6a8Sap60Loe1yYaWgIjtDRZJo3IAPJiUTU/wBD11NHQP89K7hA==,iv:PJ0OlNeIc7O9xWA2V/HdvmTNIy/obvm3iBx/OHwJ6M8=,tag:pzngTPdU8gp1Xc/jUsozzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObWlLQ3FBYm5LWlhWWGYz
            UURtU1JEQVJnTGJhd2hWTE1pdEhwNVNSelJFCnBKZGhobE9qMEsxa2hjRFlLMDBJ
            eE0yVTdnemlqeW1IdzZtVElqTzlqZlEKLS0tIDU1VHViTVcrUXFER1dkS1pqOENC
            Q3BrWGpTWkRmUUZCZktUNmh3UTJQcDgKtHIdVoaUruAUgg8DSecEKzqTn9b5X6bf
            C2i+OQEW14gpuA3PRzulUMiNeImGdfoAn4pmb1xCS2uEGseubK7LkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1caym0gc3knvhaqp4sym5l2lznrua04pjw648rl607rzkwgy2xelq9el2nn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T00:05:08Z"
    mac: ENC[AES256_GCM,data:+jQ5umtwpx5naPJmyuiimLY/H57mSVYu6mBnzrrkh67uXkVwaH07803xaD8cKwIE3j20I+qrMT2PllNWCc3jeb/5YoEASzQMhURH5VWFrJZC7xnay2NL9cSQ2erwY8mOxSwXqb2lkFpkjMsdlPdKJGI+0yBxCOApOV22gpNbsCY=,iv:JEo45lxjtgxatBILnokW5rzHOR0s5spxPnXx+3bEjYc=,tag:lD0PJUzEn5dPO7Cwvh+caw==,type:str]
    version: 3.13.3
