apiVersion: v1
kind: ConfigMap
metadata:
    name: cloudflared-config
    namespace: cloudflared
data:
    config.yaml: ENC[AES256_GCM,data:rYwyuNbFrVLrLHcnFAv+a4hVftKFPjEaU6WXcKGIffunvtXj5bH1DY9pBBx0fbBBJzNkaDHP/ysMeqXfpKsOCYb62Ie3wMcahnQx21/j4yVksqQRav7jHopTHDmmHQ3HaGYUNXF5+1XqnxWNXWdyB6R+5Xv56s30YgVZm9uDMFGr6mfciR7AGH3D2RSgSg42uBVRYaMoPMLhadLuWcuhIDp/Y3E+2PE9DdfXHN8TPis1GxLHXeyGsoQ8xrdP8RabM/1IDgw5lk26/GBzbR6ESu2P8y/KL2n6llfeB1VPLEM6xoQL/O0jxdV0jV3j9wQo/ruERj8R6T+u/aQI+W5t8G2BUm71MFgLqIcS0NMr3LQPiFvXoFGeSdS+CODE2enguUlElXauUiNmrBaCLMjFtjrM4GE/pGoZsTYUEheNfe3r/ZZunZDxc6lLbwX05CbmxW8Us/hhbGyo0rUSuQMWdnKT/LStN4fhcE/JYrWDs10mstWFySz/XTcIWwBoHtRmZEiDlPMKjLAyZ8WczeR9rz9kYwO0O6Z+w1jziO2qbNt6MG8vwDzv5/UUZJFSx0yFsoZhvvfcEOO64W3TN69fNblFuFQG1VyHZbNGQOguYGWt9cdib8U04V3s2pI1VWmRyTkhiwPO1DOroVRL2M7p1ub3HIhJICJ1/T9CR92Pzb9egcng73tN3Ds65LQis7yLwcKWI7FN+QDrWCPgb2UsBYTHNjpQAcvRU+niplTdRcjbAR4Xo5sofG+L2KZgzFp1/Tu1+DnC/B6A/9qqDY9hxRhNVs+hqph6rBkxRFIYmzcpSOFnoNIkcoWGqfVq+lOouWqbYztc+2qkAXN2wuPnRlqXf9R8crl2QSME9zNZdq77,iv:JGuxftQ+RC8dx+KSAGXWbZkjX3oSHlO54p2IPkJonhU=,tag:/c/WUdNSu/gcDZOAzY7hcg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWm9BaVkzSDI0RS9UK0lC
            eVhuSXUvZm0xUVZ4NzBsbXNjbWFoRmFEOEI0CmUwVTV5OGhFSFlQYnAyci9nL0JN
            enhPV09Eb1Y0bGxwc3pZeDBXUDMvUE0KLS0tIHNpcUVUOGNOaXZTYjArbzF2TGQy
            c0ZCRzQyejBYRjgvMlluU1lLbnhvSDQK8gWIzgeW8yMe1/ajGtrTjhZvTZZuIvjM
            HE0vtqDLMxE4pSNhquVJhYDNb4KuhIDpBcrZdbB8t9X9kCYnQQUydQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1caym0gc3knvhaqp4sym5l2lznrua04pjw648rl607rzkwgy2xelq9el2nn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T13:37:55Z"
    mac: ENC[AES256_GCM,data:ZjP+rvfyWsp1Mw00h71vse9Rq1aPOcjYr3ZQh5boeAb+tCgIS8CFmuMIRzWn6EM1eXvnrRjjTgpeSElfJbSP1x3Eg0f7XYaJDTN1Cw4PmsYk5kw1RVcDdWzLyAmYPOYiz+8g+F0RhFzv//AasKPLrt8pIqQunf82ESi3whVAg7s=,iv:IPIZS6U2zaAgRBP1PFqBa/x7u2dKKq8I7YFPtLFouUw=,tag:M0fPIZnoX+S9BEXkpGxb6A==,type:str]
    version: 3.13.3
