apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared

resources:
  - cloudflared.yaml
  - cloudflared-ns.yaml
  - cloudflared-configmap.enc.yaml
  - tunnel-credentials.enc.yaml