apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:DChD9U5oKeHK/kQyU8HKFeTniF9Zv7d58mrnzR/51B9J1cJUkj5wTSPQu9WW/HJSa1SJzx+gwNmUwtkDxc2YK6XS+cLsvFeLGbtin/jnPLLybTVTB9Y9CVWxrRG1URnuimXqkH7+Wp+Uckik8hGf8sWRS0odJjLQHh0i9LYx1cyz1tK89WW0hqOBPnYm7AQlm/HYh5lim9JmBaar4Ys88swQG+hTC6YQDddMldb6ToJEiVhLMqq+pyzHq9tVoC6K8onCZSKazgVBtW6CYVvomyX/a8Mv3qpqPYuM3sz2k9KCU91/4WuPJ4qY+xo=,iv:7qBx0JR6wbkaCDHigpgFbgQKH8W9jVFyD5eSteyVZsQ=,tag:qMw10F4jvLuTkoJPewmLlg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: cloudflared
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibHVNcWcvdkN2TkhLbUZw
            M0RzZUFLS25OYmxzVXNjWVdiOFU1SjV4MkZvCkFWWENkVGJTaWVxaFg2TnhzcHk0
            R3lkQmRjSTVLRmJlN0FqOUlRVEswRjgKLS0tIHE3OEp0dVd6L3JPdVk5SkVpeVM5
            ZWlmbWFZVVB1NS9ieEtuNE5mOHozSTQK3oM5FTsZY6NO1TkZDu/nlKmND3NVPlJO
            dhI9NF9On5+DZvORRJwIQYNqRsMCMxqQhqIAjtMC0T4Pp5QKM83J8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1caym0gc3knvhaqp4sym5l2lznrua04pjw648rl607rzkwgy2xelq9el2nn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T20:30:58Z"
    mac: ENC[AES256_GCM,data:GiJ5+6+n5i6tyDwvOY5vrZyCPwXdHfBSH6Cg3WBqdYiXWxLsWU3rDEzQ4vhx4qTFwOAmVGEr09eMIbRRVf3BCQsFDqDY/fb7+CM3stLkMFZp9jDzwH/iQYTibpZgR9niTcK9bMb1+BM+/mbyP93sOw0frKE3O66l42LMHz8Vmn8=,iv:IRPsEyGdVqzYrshTQ67FmavjPcvkjfFEAOllA5u0kfM=,tag:1LyZyFsb0S8SQNio0pKeWg==,type:str]
    version: 3.13.3
