apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
  name: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      securityContext:
        fsGroup: 911

      containers:
      - image: ghcr.io/mealie-recipes/mealie:v3.22.0
        name: mealie

        securityContext:
          runAsUser: 911
          runAsGroup: 911
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL

        ports:
          - containerPort: 9000

        volumeMounts:
          - mountPath: /app/data
            name: mealie-data

      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-pvc