apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  template:          
    spec:
       # --- POD-LEVEL SYSTEM & KERNEL HARDENING ---
      securityContext:
        runAsNonRoot: true        
        runAsUser: 1000            
        runAsGroup: 1000            
        fsGroup: 1000            
        seccompProfile:
          type: RuntimeDefault   
