apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-password
    namespace: monitoring
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:f5q+a61T2p4ajK5KkX+c,iv:PfJUfiSscqP6r2bmbhgYZ9d/7S3wJb9HwoZfKVGdCis=,tag:Z2YHRDrG/12iCkI/IP9Fug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvN2RXcHVic2NXZ01mR1pq
            empKdTgyOUpkbTFFYUNlZy9yWGoxMU1YemdnCnRwSlBUNWVIYk5udDZLZGQ4Wm0w
            bjNMRjhMMGlSWVA3NnNQclpaM0ttaTAKLS0tIEdYSXp5Y1A0Y1k3NFM0N0RqcXhh
            dzJxdzdGSllYWmhzT3ZwNkdiaTdDWTQK4k7ZPmSkjRkgtoP/UeJd2430ddFRoEMH
            y/arud6E6F/MROLOqpJA/D32eX7Yu/JRbkKvZbCn18BoZ9UqStGJ0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1caym0gc3knvhaqp4sym5l2lznrua04pjw648rl607rzkwgy2xelq9el2nn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T11:56:43Z"
    mac: ENC[AES256_GCM,data:WalkZpRqEX7fa1Us9i2zJXUz6pueNgpbXwwSdd0tfuapFjpOQasCZg1czi1s+DW/tc5ExkRN5BOHQxmeeDpl5P0v+MEqgXKqY5FM0JLigeUvH0QInwX85clyRfkr+pS/xtUu3BmSWy8mHZJlLxdHr5TSsYvfhVyv++8JgOWT6rM=,iv:JhUfIoJol4Q1vPlPEhiE/QzKXCabQbqoPRdB5daF3gE=,tag:NFsXZr3Xt1jq6OYu5uL7Ew==,type:str]
    version: 3.13.3
