apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  template:
    spec:
      containers:
      - name: linkding
        volumeMounts:
        - name: linkding-storage
          mountPath: /etc/linkding/data
      volumes:
      - name: linkding-storage
        persistentVolumeClaim:
          claimName: linkding-pvc