apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  template:          
    spec:
       # --- POD-LEVEL SYSTEM & KERNEL HARDENING ---
      securityContext:
        runAsNonRoot: true        # Enforce: Blocks the container from starting if it defaults to root (UID 0)
        runAsUser: 33             # Identity: Configures the process to run explicitly as the 'www-data' user account
        runAsGroup: 33            # Identity: Configures the process to run explicitly under the 'www-data' group account
        fsGroup: 33               # Permissions: Automates host storage mounts to be read/write accessible to GID 33
        seccompProfile:
          type: RuntimeDefault    # Sandbox: Restricts dangerous low-level Linux system calls to the host kernel
      containers:
      - name: linkding
        volumeMounts:
        - name: linkding-storage
          mountPath: /etc/linkding/data
        env:
          - name: LD_SUPERUSER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: linkding-pass
                key: LD_SUPERUSER_PASSWORD
          - name: LD_SUPERUSER_NAME
            valueFrom:
              secretKeyRef:
                name: linkding-pass
                key: LD_SUPERUSER_NAME
      volumes:
      - name: linkding-storage
        persistentVolumeClaim:
          claimName: linkding-pvc
