apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:lDv/aGWC1Mxx6eym,iv:RekM7m4AFWlzPkMGjwo/uNcDcp/EQCd/FyMs25MJ5x8=,tag:b1zi/Hyt7n5k/1nYn7evKA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:3W2N9MEmEThkBUBW,iv:20YwOcQYLbe/yiiGfzsuAnCvJ8HuzFGb5GRdsCStEq0=,tag:yiDgFCaOvtKYTk8TFa0+eQ==,type:str]
kind: Secret
metadata:
    name: linkding-pass
    namespace: linkding
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaHJrVGs1bm9UT0Z2WHBN
            SklWcmJBdWlCeTE4VHlTNWxTRXpBUEkvUkFVCkJvMTVPRzhJVnVLdDBYMEQyZWNk
            U0RTYnM3WEg4NThadDFRTHlsQUtXZVEKLS0tIEZuZnpXY1VIeTlaZTFtRkVoUDE4
            bUp5RnY2M1RHVEVBZjJhQkp6aGtYSlEKyciO6FfPTSVnJzZaOpNFR71AsOqWbo44
            YC/wkRnow5OdeiTorHenxkJUi+juHXabTdsUsUVfV3Y3SOc9Ib/w8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1caym0gc3knvhaqp4sym5l2lznrua04pjw648rl607rzkwgy2xelq9el2nn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T20:24:18Z"
    mac: ENC[AES256_GCM,data:/lXONyqa/mCC2Gb07582w9hgV7Ti9jaSPtqI97H/H/SE5iFTSjzX4vh0F2+R41A5SKf6WTFBlWFM2AWU6KvFJZppipUfLDs974Y4bvH5AYh/irOK2HL+SWStiTZhtk0rKvp8ZKpH6QS1cZdsDIoYEOryiymmkUGJqHYnhdNLbVg=,iv:KLoC90cfFwaPszJog1UUuYvUVk8gaWDvMLax3sgkutw=,tag:ogzNI1Z/Xf3duGKqMz3ysA==,type:str]
    version: 3.13.3
