apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:GWi5PcLD+0gryuM0,iv:YFB5DHQXe1EkkrPy8Pi6tIuXrsLTbh35AsAXrCSUAPM=,tag:idrsa+xR8Y2kRnsUGBq6lw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:0ALa/C2iGw9348j3,iv:nQwEJwAOKCLB56fFPq2mg+NwwZj8vdTqvb0toQe/zCg=,tag:UyHqdY9KvwTMLYaSVUb/Fg==,type:str]
kind: Secret
metadata:
    name: linkding-pass
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eHpYSjdvemxUWE1hUWxB
            TENnZWg2WWpDcjNMSjNMMGxGUVFvWDB2ZmcwCkV1WmFyTGZ0U3FnK3lFblRadlYz
            UlNyd0czdk45L2tCT0xxNWN4WSsrdzAKLS0tIEFueEdOZGc0ZlFlSk9YeTRNdytC
            Q1FmdDV4K1ZsZ3hqa1VxaHM2SXUzSjQKiViT4DN66UlFbhVo4AKHuovvsoHgMWUQ
            mUv2AXHKq1jEeXteUjEgYtbKFLtSuGDjNR0vwPnBmfYVz+4Dj5H66g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1caym0gc3knvhaqp4sym5l2lznrua04pjw648rl607rzkwgy2xelq9el2nn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T21:25:39Z"
    mac: ENC[AES256_GCM,data:yhaciY1EKoR7X+4FcphC2MEhLXt74psrycN14A+vpRcfCJ65kNgX8egVQt/Po/GcFX1fPICad9hM/hJPfFckTSn5VrJEcwv8dSANOpV9pNiKhA0ZWQzw6UUiOpnsRSO2mXaQuMmXgxkHimmn+AeSFT1QEalCLIIFdJqFnnoiSi8=,iv:/21mM77Ubqitq8sEh3Ydy93P2g2T55fauGZcRtp9bzU=,tag:XFTUpp2I0SLq0PZbP5PKiQ==,type:str]
    version: 3.13.3
