apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:OA+yEWzOP2LrGa48KvS4cg6UxOpNB+SirOFKHAywTJLn3u8DNsimMJBrdd92mI5gULerNgRtVHeoMD4W+h8XVVYYMqZHZO/xhuKOMOe8gYrxB1sUaSN6m1+jU3Ij4y7rNJDbSlzuZKPYeOFhrZSVaVeXw1/XlJ015WOk61E7Rccrwg1zlg5oDIxMjSmyDibT11UvCJ8qjicZ2iWmQuVFac7plv1+VsqBO+WLraZfvcZ9kErRmFYD+AWlpHv0X08KjyRTPa/8BEm7Ttf006bLTtjtXD0lKgNwT56BMVcSVpJuoZw8j7+HQOVuQMbkHQpBaWLDGyNonpmWaq+2WJU5TziHmjodTaQ0,iv:HGlYbrYXeeJ8BwYAXgIhCnfG/wZoMzUotsL/1lqaagU=,tag:SAr5wOoXDV51v5yEUCxRXA==,type:str]
kind: Secret
metadata:
    name: dockerhub-registry
    namespace: portfolio
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMajZmczlaT0VpSEtrNjdN
            dmdCaHJJWTAwUll0TDFPZ3lBV0ZKOUh4SUhZClB1b3ZGeG51bWVucGZzaU1tQ01Y
            d0tuMXJwTVNreXJ0TVZhL3pzZVZFVzAKLS0tIEh0NXc3UTBFRVh3VUdiVkg2YjZE
            WHpMUmtnUlJpT0J4b3FYSG5adlJFZ2sKlGUdsNKKK2LTabrxxVCefutyx53qk7k9
            5tpeiQlqcY63LyWTsFUtuqCaKH/KV5ogdJEqsdEYKkkBwt83p3E8og==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1caym0gc3knvhaqp4sym5l2lznrua04pjw648rl607rzkwgy2xelq9el2nn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T03:16:26Z"
    mac: ENC[AES256_GCM,data:QWb1Dg8ErxGjbky0VGT20DiO8ecG3sbnf9g7Isg4TsBhaVFQXghZobMgAEJ0OxzEZTSFzdkz5k22tacISVWO8LTkwKoa4TV/3r5J7a6HyzWPjeCH4+xK5aNYQ74QNlLII0KMacFEsoBE2KY9sXRbp0T212pPMb159lnSrNAt4Co=,iv:HGjpIsbCw23GL6k8bcWf3SKqTmY+ZElZ3F3+/EKrSs0=,tag:J6YWPBraeCX3fvxw6bGxAA==,type:str]
    version: 3.13.3
