apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:vacXdnIPBBxjHjXGKFyfjQoPArt0TgB4x0FhnRY2Sjy+LblNw0HGOjTfwaSnxoB2gLnN4L3E+Lo=,iv:0IdYXx/wgHioQF3F962RRN7QmEIG3QC9SRvWds9pyok=,tag:w+BiVh9a6MdQTVx8gVjI+g==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUenMyZitKdWl6eWlqa3or
            SC9FQmRTZklqakU4d2JQQy9MZkxWMWo2Q0E4ClRJZ3IvSzlHSHlEVEQ1V3UwZnVr
            bUxQcWwrekl2M0VYbjE0VnFHZ0JkZ2MKLS0tIG9GUGtCTTROSFU4a281bCtDZVBM
            SDFHQTMxSkdmQXl0LzBWYXBIUTgyV00KcjHhhppiiLWnfGD9QBpFvPaJDD9idHtS
            I2YJ1SuJJGpqHZaLK6v2BuWyYsYPH2RtahAYtAxAbyUjl9u7qU/BgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1caym0gc3knvhaqp4sym5l2lznrua04pjw648rl607rzkwgy2xelq9el2nn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T23:31:07Z"
    mac: ENC[AES256_GCM,data:hgvuFgEa5c04Eq73c0ZSjfEWNItELbOQFX2C5kyZetC5d1q3ZIi2tPgLmfEqUufbe/D10YY2e7URdEtuPSQYAgFqEhDftsKKQ8kqYmunOvw8xFY1z48uKDlAdcGnxN1Nm4WJj8YtDzcLXj/YXzcjiI1XIofKg9a+5cvWTqu+15Y=,iv:BgxDhyRA/3+RBPAKKbb03JP3P5FxcJXLKodFmcefLqk=,tag:p19R4Oa0TVuF2wGg53fzjA==,type:str]
    version: 3.13.3
